version: '3'
services:
  app:
    build: .
    container_name: nodejs-app
    ports:
      - "3000:3000"
    volumes:
      - .:/server/index
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    
